name: CI/CD Pipeline for MERN Stack Ecommerce App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    name: "🔧 Format & Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint

  backend:
    name: "✅ Backend Tests"
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Test Backend
        run: |
          npm --workspace backend ci
          npm --workspace backend test

  frontend:
    name: "🌐 Frontend Tests"
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Test Frontend
        run: |
          npm install
          npm test

  complete:
    name: "🎉 All Tests Passed"
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]
    steps:
      - name: Notify success
        run: echo "✅ Backend and frontend tests all passed."

  docker:
    name: "🐳 Build & Push Docker Images"
    runs-on: ubuntu-latest
    needs: complete
    permissions:
      contents: read
      packages: write   # for GHCR publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mern-ecom-backend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mern-ecom-backend:latest

      - name: Build & push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mern-ecom-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mern-ecom-frontend:latest
